# docker-compose.yml
services:
  api:
    build: ./backend
    image: smart-librarian-api:local
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    command: sh -c "python ingest.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()"]
      interval: 10s
      timeout: 3s
      retries: 10

  web:
    build: ./frontend
    image: smart-librarian-web:local
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
